language: python
sudo: true
python:
  - "2.7"

install:
  - sudo apt-get install -y rpm

script:
  - pip freeze  # so to help eventual debug: know what exact versions are in use can be rather useful.

after_success:
  - echo "Packaging for BinTray - Debian..."
  - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION deb
  - echo "Packaging for BinTray - RPM..."
  - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION rpm

deploy:
  # PyPi deployment for tagged commits:
  # -> build a PyPi package when a version is set
  # Bintray deployment for develop branch and tagged commits:
  # -> build Deb/Rpm packages on develop branch or when a version is set
  - provider: pypi
    distributions: "sdist bdist_wheel"
    skip_existing: true
    on:
      tags: true
    user: alignak
    password:
      secure: "gpZz5XmGDw3/PE5UBosv7ER7MzLecnkmn/JL23kdqDHAptNI1ysOVMT1E4t/XNkuqH+Qcc8Vl0vkuT9F0/BrcfRkeKSLXnhK2YSo7xFLheVY5luo0Kmz+S4zZC7oXngiHX5cCGmYyU0DZ/RGwNUV1N/Q82fzRtXULRRPYRB45xYWEBWiJVC0PhK4LHMYL+U03IGiCNFN3hQC2OR1wPl8IJa+fAgNB6vtr4ufXYVtGUVP/hL0GrsefSP6jekyY4Ae5ZeM6gPMza08jdHijCPecJ1dyD/pZ6pbaQeFO5Ui8bj2xjgDOM3oyWaQmb22IWWJ0JraHYuDMLGth49jnmOHh4qEaNC4VqKNC/Ix/i6GrmOLLCBQKQLKR6f8SxEmwVjmOOIEmfoTTx/QyCpHUVavUOIdGQegz6fq3EcaGKwe6rOFJBTD9JzLbeRcDFv4hCjauYbuMIYOn8wzn/MXFdkNBNz09UiuF79xemy42jOrbSFn2jFqWbMU9R2sUjFPSbvrUGb8ROcPXPGygOtUuOqASp1FT4VE9FHuTv79pz6tRR+tM5SJCuoTqrFO7EGKuyKSgDsP2gYM3bamuYGCDCAegGXzG4GShLJYytZgXebUUEwHVdGy7mIRKCvLEliLIC4zzQm1qGaqOPA7jTY2llO6V2VwoAkI2b5lTFiiL/xSJYU="
  - provider: bintray
    skip_cleanup: true
    file: dist/.bintray-deb.json
    user: mohierf
    key:
      secure: "k5IwsU4diiBWyF68gvbAWgSKEk/ARPejFE/9Naj338ek+5c8NX6NtdH+C7fyiDnceaNQGJA9y7hsJIJWyue9vDZXvLiixDnaJxXwvssSM1dCfAOZA/kHG4Eb21VPhywp+SbejV0zhIpLE675kbZzjwFK0Iq4pjAxc25uDAIAJ9mH1nKtxOIdoX4Lv7CMfNV6MalZ7QkLsq5JLTM8522w7ihQypKfq7MGq2rVOFToRc04SdoVdyzr8GD7vbNfB96ZBpcOu2hy+BkqGPFEK09/E1ccyfJUoOQ65X45WTKKuOYa1kk31nuY1AXdLpKMq8JUWC0MNyi7vmrHUdveyxXqBEZNDqWZXEHc9/cBfrlBRByuNjxAa867fZ+T1vhp0vJsyXjhqcXaat7oUJM8VhxayPx5sb/BGJLU9e6ktL24oKX1CktcBEum2NRd8EvfrfsPSEIf1moFWT+oh9BfZGykVTXnuj4rEtapFiOxcK9ywLKbwy8xMFhRkmwshqn4BaMjgrMVw6Fj+tls4HmSR02Oj0JscUiZp4lu6SINqQAcG91LS3qzMErNMDNH8yVfzW9wHrlg/c6N1+DnR9nJfmXowylEV6LrwdbRwLCQhEIJ4Z+N2WzNqH6ALp4KPORGQ5NyPvtDb5Ntz9Wc4KyVi/q8ftqlxFxZp9cwUonX3Y3l4+M="
    on:
      all_branches: true
  - provider: bintray
    skip_cleanup: true
    file: dist/.bintray-deb.json
    user: mohierf
    key:
      secure: "k5IwsU4diiBWyF68gvbAWgSKEk/ARPejFE/9Naj338ek+5c8NX6NtdH+C7fyiDnceaNQGJA9y7hsJIJWyue9vDZXvLiixDnaJxXwvssSM1dCfAOZA/kHG4Eb21VPhywp+SbejV0zhIpLE675kbZzjwFK0Iq4pjAxc25uDAIAJ9mH1nKtxOIdoX4Lv7CMfNV6MalZ7QkLsq5JLTM8522w7ihQypKfq7MGq2rVOFToRc04SdoVdyzr8GD7vbNfB96ZBpcOu2hy+BkqGPFEK09/E1ccyfJUoOQ65X45WTKKuOYa1kk31nuY1AXdLpKMq8JUWC0MNyi7vmrHUdveyxXqBEZNDqWZXEHc9/cBfrlBRByuNjxAa867fZ+T1vhp0vJsyXjhqcXaat7oUJM8VhxayPx5sb/BGJLU9e6ktL24oKX1CktcBEum2NRd8EvfrfsPSEIf1moFWT+oh9BfZGykVTXnuj4rEtapFiOxcK9ywLKbwy8xMFhRkmwshqn4BaMjgrMVw6Fj+tls4HmSR02Oj0JscUiZp4lu6SINqQAcG91LS3qzMErNMDNH8yVfzW9wHrlg/c6N1+DnR9nJfmXowylEV6LrwdbRwLCQhEIJ4Z+N2WzNqH6ALp4KPORGQ5NyPvtDb5Ntz9Wc4KyVi/q8ftqlxFxZp9cwUonX3Y3l4+M="
    on:
      tags: true
  - provider: bintray
    skip_cleanup: true
    file: dist/.bintray-rpm.json
    user: mohierf
    key:
      secure: "k5IwsU4diiBWyF68gvbAWgSKEk/ARPejFE/9Naj338ek+5c8NX6NtdH+C7fyiDnceaNQGJA9y7hsJIJWyue9vDZXvLiixDnaJxXwvssSM1dCfAOZA/kHG4Eb21VPhywp+SbejV0zhIpLE675kbZzjwFK0Iq4pjAxc25uDAIAJ9mH1nKtxOIdoX4Lv7CMfNV6MalZ7QkLsq5JLTM8522w7ihQypKfq7MGq2rVOFToRc04SdoVdyzr8GD7vbNfB96ZBpcOu2hy+BkqGPFEK09/E1ccyfJUoOQ65X45WTKKuOYa1kk31nuY1AXdLpKMq8JUWC0MNyi7vmrHUdveyxXqBEZNDqWZXEHc9/cBfrlBRByuNjxAa867fZ+T1vhp0vJsyXjhqcXaat7oUJM8VhxayPx5sb/BGJLU9e6ktL24oKX1CktcBEum2NRd8EvfrfsPSEIf1moFWT+oh9BfZGykVTXnuj4rEtapFiOxcK9ywLKbwy8xMFhRkmwshqn4BaMjgrMVw6Fj+tls4HmSR02Oj0JscUiZp4lu6SINqQAcG91LS3qzMErNMDNH8yVfzW9wHrlg/c6N1+DnR9nJfmXowylEV6LrwdbRwLCQhEIJ4Z+N2WzNqH6ALp4KPORGQ5NyPvtDb5Ntz9Wc4KyVi/q8ftqlxFxZp9cwUonX3Y3l4+M="
    on:
      all_branches: true
  - provider: bintray
    skip_cleanup: true
    file: dist/.bintray-rpm.json
    user: mohierf
    key:
      secure: "k5IwsU4diiBWyF68gvbAWgSKEk/ARPejFE/9Naj338ek+5c8NX6NtdH+C7fyiDnceaNQGJA9y7hsJIJWyue9vDZXvLiixDnaJxXwvssSM1dCfAOZA/kHG4Eb21VPhywp+SbejV0zhIpLE675kbZzjwFK0Iq4pjAxc25uDAIAJ9mH1nKtxOIdoX4Lv7CMfNV6MalZ7QkLsq5JLTM8522w7ihQypKfq7MGq2rVOFToRc04SdoVdyzr8GD7vbNfB96ZBpcOu2hy+BkqGPFEK09/E1ccyfJUoOQ65X45WTKKuOYa1kk31nuY1AXdLpKMq8JUWC0MNyi7vmrHUdveyxXqBEZNDqWZXEHc9/cBfrlBRByuNjxAa867fZ+T1vhp0vJsyXjhqcXaat7oUJM8VhxayPx5sb/BGJLU9e6ktL24oKX1CktcBEum2NRd8EvfrfsPSEIf1moFWT+oh9BfZGykVTXnuj4rEtapFiOxcK9ywLKbwy8xMFhRkmwshqn4BaMjgrMVw6Fj+tls4HmSR02Oj0JscUiZp4lu6SINqQAcG91LS3qzMErNMDNH8yVfzW9wHrlg/c6N1+DnR9nJfmXowylEV6LrwdbRwLCQhEIJ4Z+N2WzNqH6ALp4KPORGQ5NyPvtDb5Ntz9Wc4KyVi/q8ftqlxFxZp9cwUonX3Y3l4+M="
    on:
      tags: true
